{{ $fullname := include "presidio.analyzer.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- with (merge .Values.analyzer.deploymentLabels .Values.commonLabels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.analyzer.deploymentAnnotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.analyzer.replicas }}
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.analyzer.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.analyzer.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.analyzer.service.internalPort }}
        resources:
          requests:
            memory: {{ .Values.analyzer.container.resources.requests.memory }}
            cpu: {{ .Values.analyzer.container.resources.requests.cpu }}
          limits:
            memory: {{ .Values.analyzer.container.resources.limits.memory }}
            cpu: {{ .Values.analyzer.container.resources.limits.cpu }}
        env:
        - name: PORT
          value: {{ .Values.analyzer.service.internalPort | quote }}
        {{- with .Values.analyzer.environmentVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.analyzer.extraVolumeMounts }}
        volumeMounts: {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.privateRegistry }}
      imagePullSecrets:
      - name: {{.Values.privateRegistry}}
      {{- end }}
      {{- with .Values.analyzer.extraVolumes }}
      volumes: {{- toYaml . | nindent 6 }}
      {{- end }}
