{{ $fullname := include "presidio.anonymizerimage.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    service: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- with (merge .Values.anonymizerimage.service.labels .Values.commonLabels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.anonymizerimage.service.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.anonymizerimage.service.type }}
  ports:
  - port: {{ .Values.anonymizerimage.service.externalPort }}
    targetPort: {{ .Values.anonymizerimage.service.internalPort }}
    protocol: TCP
    name: {{ .Values.anonymizerimage.service.name }}
  selector:
    app: {{ $fullname }}
