{{- if .Values.db.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "supabase.db.fullname" . }}-migrations
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.db.config | nindent 2 }}
{{- end }}
