{{- if .Values.functions.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.functions.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.functions.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.functions.autoscaling.enabled }}
  replicas: {{ .Values.functions.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.functions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.functions.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.functions.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.functions.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.functions.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.functions.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "supabase.waitForDB" . | nindent 8 }}
      containers:
        - args:
            - start
            - --main-service
            - /home/deno/functions/main
          name: {{ include "supabase.functions.name" $ }}
          securityContext:
            {{- toYaml .Values.functions.securityContext | nindent 12 }}
          image: "{{ .Values.functions.image.repository }}:{{ .Values.functions.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.functions.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.functions.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: POSTGRES_HOST
              value: {{ include "supabase.database.host" . | quote }}
            - name: POSTGRES_PORT
              value: {{ include "supabase.database.port" . | quote }}
            - name: POSTGRES_SSL_MODE
              value: {{ include "supabase.database.sslmode" . | quote }}
            - name: POSTGRES_USERNAME
              value: {{ include "supabase.database.supabase_username" . | quote }}
            - name: POSTGRES_PASSWORD
              {{- include "supabase.database.password" . | nindent 14 }}
            - name: POSTGRES_DB
              value: {{ include "supabase.database.db_name" . | quote }}
            - name: SUPABASE_DB_URL
              value: postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=$(POSTGRES_SSL_MODE)
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.anonKey | default "anonKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: anonKey
                  {{- end }}
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.serviceKey | default "serviceKey" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: serviceKey
                  {{- end }}
            {{- if .Values.kong.enabled }}
            - name: SUPABASE_URL
              value: http://{{ include "supabase.kong.fullname" . }}:{{ .Values.kong.service.port }}
            {{- end }}
          {{- with .Values.functions.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.functions.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.functions.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            # We need subPath to get rid of symlinks
            - mountPath: /home/deno/functions/main/index.ts
              subPath: index.ts
              name: functions-main
          {{- with .Values.functions.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.functions.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: functions-main
          configMap:
            name: {{ include "supabase.functions.fullname" . }}-main
      {{- with .Values.functions.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.functions.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.functions.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
