registry: mcr.microsoft.com

# Image pull secret
# privateRegistry: acr-auth

# supported types are nginx (wip: traefik and istio)
ingress:
  enabled: true
  class: nginx
  annotations: {}
  labels: {}

# For any of the services below, a service mesh like Linkerd or Istio
# is needed to properly balance traffic to more than 1 replica.
# https://github.com/microsoft/presidio/issues/304

commonAnnotations: {}
commonLabels: {}

analyzer:
  name: presidio-analyzer
  tag: latest
  replicas: 1
  imagePullPolicy: Always
  container:
    resources:
      requests:
        memory: "1500Mi"
        cpu: "1500m"
      limits:
        memory: "3000Mi"
        cpu: "2000m"
  deploymentAnnotations: {}
  deploymentLabels: {}
  extraVolumes: []
  extraVolumeMounts: []
  environmentVars: []
  service:
    annotations: {}
    labels: {}
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    name: http

anonymizer:
  name: presidio-anonymizer
  tag: latest
  replicas: 1
  imagePullPolicy: Always
  container:
    resources:
      requests:
        memory: "128Mi"
        cpu: "125m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  deploymentAnnotations: {}
  deploymentLabels: {}
  extraVolumes: []
  extraVolumeMounts: []
  environmentVars: []
  service:
    annotations: {}
    labels: {}
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    name: http

anonymizerimage:
  name: presidio-image-redactor
  tag: latest
  replicas: 1
  imagePullPolicy: Always
  container:
    resources:
      requests:
        memory: "1500Mi"
        cpu: "1500m"
      limits:
        memory: "3000Mi"
        cpu: "2000m"
  deploymentAnnotations: {}
  deploymentLabels: {}
  extraVolumes: []
  extraVolumeMounts: []
  environmentVars: []
  service:
    annotations: {}
    labels: {}
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    name: http
