{{- if .Values.rest.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.rest.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.rest.service.type }}
  ports:
    - port: {{ .Values.rest.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.rest.selectorLabels" . | nindent 4 }}
{{- end }}